// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GPRCTemplateClient is the client API for GPRCTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPRCTemplateClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type gPRCTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewGPRCTemplateClient(cc grpc.ClientConnInterface) GPRCTemplateClient {
	return &gPRCTemplateClient{cc}
}

func (c *gPRCTemplateClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.GPRCTemplate/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPRCTemplateClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/pb.GPRCTemplate/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPRCTemplateServer is the server API for GPRCTemplate service.
// All implementations must embed UnimplementedGPRCTemplateServer
// for forward compatibility
type GPRCTemplateServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedGPRCTemplateServer()
}

// UnimplementedGPRCTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedGPRCTemplateServer struct {
}

func (UnimplementedGPRCTemplateServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGPRCTemplateServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGPRCTemplateServer) mustEmbedUnimplementedGPRCTemplateServer() {}

// UnsafeGPRCTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPRCTemplateServer will
// result in compilation errors.
type UnsafeGPRCTemplateServer interface {
	mustEmbedUnimplementedGPRCTemplateServer()
}

func RegisterGPRCTemplateServer(s grpc.ServiceRegistrar, srv GPRCTemplateServer) {
	s.RegisterService(&GPRCTemplate_ServiceDesc, srv)
}

func _GPRCTemplate_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPRCTemplateServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GPRCTemplate/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPRCTemplateServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPRCTemplate_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPRCTemplateServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GPRCTemplate/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPRCTemplateServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPRCTemplate_ServiceDesc is the grpc.ServiceDesc for GPRCTemplate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPRCTemplate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GPRCTemplate",
	HandlerType: (*GPRCTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GPRCTemplate_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GPRCTemplate_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
